/*
 * Generated by tools/convert_nice_view_art.py.
 * SPDX-License-Identifier: MIT
 */

#pragma once

#include <lvgl.h>

LV_IMG_DECLARE(atmos_atmos_mark_head_generated_v1);
LV_IMG_DECLARE(atmos_avatar_wave_v1);
LV_IMG_DECLARE(atmos_avatar_explorer_v1);
LV_IMG_DECLARE(atmos_avatar_observer_v1);
LV_IMG_DECLARE(atmos_avatar_leader_v1);

#define ATMOS_ART_FRAME_COUNT 5

static const lv_img_dsc_t *atmos_anim_imgs[] = {
    &atmos_atmos_mark_head_generated_v1,
    &atmos_avatar_wave_v1,
    &atmos_avatar_explorer_v1,
    &atmos_avatar_observer_v1,
    &atmos_avatar_leader_v1,
};
