#!/usr/bin/env python3
"""Convert PNG/JPEG/WebP images into LVGL 1-bit nice!view slideshow art.

Run with uv, for example:
  uv run --with pillow tools/convert_nice_view_art.py \
    --output-c boards/shields/nice_view_atmos/widgets/art.c \
    --output-h boards/shields/nice_view_atmos/widgets/art.h \
    --preview-dir outputs/atmos-preview \
    --preview-inverted \
    --safe-width 92 \
    --margin 4 \
    path/to/image-1.png path/to/image-2.png
"""

from __future__ import annotations

import argparse
import math
import re
from pathlib import Path

from PIL import Image, ImageOps


WIDTH = 140
HEIGHT = 68
PALETTE_BYTES = 8


def c_ident(path: Path, prefix: str) -> str:
    stem = re.sub(r"[^a-zA-Z0-9]+", "_", path.stem).strip("_").lower()
    if not stem:
        stem = "frame"
    if stem[0].isdigit():
        stem = f"frame_{stem}"
    return f"{prefix}_{stem}"


def rasterize_to_canvas(path: Path, threshold: int, size: tuple[int, int]) -> Image.Image:
    src = Image.open(path).convert("RGBA")
    src.thumbnail(size, Image.Resampling.LANCZOS)

    width, height = size
    rgba = Image.new("RGBA", size, (255, 255, 255, 0))
    x = (width - src.width) // 2
    y = (height - src.height) // 2
    rgba.alpha_composite(src, (x, y))

    pixels = rgba.load()
    mono = Image.new("1", size, 1)
    out = mono.load()
    for py in range(height):
        for px in range(width):
            r, g, b, a = pixels[px, py]
            if a < 16:
                out[px, py] = 1
                continue
            lum = int(0.2126 * r + 0.7152 * g + 0.0722 * b)
            out[px, py] = 0 if lum < threshold else 1
    return mono


def fit_to_canvas(path: Path, threshold: int, rotate: int) -> Image.Image:
    if rotate in {90, 270}:
        mono = rasterize_to_canvas(path, threshold, (HEIGHT, WIDTH))
    else:
        mono = rasterize_to_canvas(path, threshold, (WIDTH, HEIGHT))

    if rotate:
        mono = mono.rotate(-rotate, expand=True)
    if mono.size != (WIDTH, HEIGHT):
        raise ValueError(f"rotated image has size {mono.size}, expected {(WIDTH, HEIGHT)}")
    return mono


def constrain_to_safe_area(image: Image.Image, safe_width: int, margin: int) -> Image.Image:
    if safe_width == WIDTH and margin == 0:
        return image
    if safe_width <= 0 or safe_width > WIDTH:
        raise ValueError(f"safe width must be between 1 and {WIDTH}")
    if margin < 0:
        raise ValueError("margin must be non-negative")

    max_width = safe_width - (margin * 2)
    max_height = HEIGHT - (margin * 2)
    if max_width <= 0 or max_height <= 0:
        raise ValueError("margin leaves no drawable area")

    line_mask = ImageOps.invert(image.convert("L"))
    bbox = line_mask.getbbox()
    if bbox is None:
        return image

    crop = image.crop(bbox)
    crop.thumbnail((max_width, max_height), Image.Resampling.NEAREST)

    safe_canvas = Image.new("1", (WIDTH, HEIGHT), 1)
    x = margin + (max_width - crop.width) // 2
    y = margin + (max_height - crop.height) // 2
    safe_canvas.paste(crop, (x, y))
    return safe_canvas


def pack_indexed_1bit(image: Image.Image) -> list[int]:
    row_bytes = math.ceil(WIDTH / 8)
    data: list[int] = []
    pixels = image.load()
    for y in range(HEIGHT):
        for byte_x in range(row_bytes):
            byte = 0
            for bit in range(8):
                x = byte_x * 8 + bit
                value = 1 if x >= WIDTH else int(pixels[x, y] != 0)
                byte |= value << (7 - bit)
            data.append(byte)
    return data


def format_bytes(data: list[int], indent: str = "  ") -> str:
    lines = []
    for i in range(0, len(data), 18):
        chunk = data[i : i + 18]
        lines.append(indent + ", ".join(f"0x{byte:02x}" for byte in chunk) + ",")
    return "\n".join(lines)


def generate_c(frames: list[tuple[str, list[int]]]) -> str:
    parts = [
        "/*",
        " * Generated by tools/convert_nice_view_art.py.",
        " * SPDX-License-Identifier: MIT",
        " */",
        "",
        '#include "art.h"',
        "",
        "#ifndef LV_ATTRIBUTE_MEM_ALIGN",
        "#define LV_ATTRIBUTE_MEM_ALIGN",
        "#endif",
        "",
    ]

    data_size = PALETTE_BYTES + math.ceil(WIDTH / 8) * HEIGHT
    for name, payload in frames:
        attr = f"LV_ATTRIBUTE_IMG_{name.upper()}"
        parts.extend(
            [
                f"#ifndef {attr}",
                f"#define {attr}",
                "#endif",
                "",
                f"const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST {attr} uint8_t {name}_map[] = {{",
                "#if CONFIG_NICE_VIEW_WIDGET_INVERTED",
                "  0xff, 0xff, 0xff, 0xff, /*Color of index 0*/",
                "  0x00, 0x00, 0x00, 0xff, /*Color of index 1*/",
                "#else",
                "  0x00, 0x00, 0x00, 0xff, /*Color of index 0*/",
                "  0xff, 0xff, 0xff, 0xff, /*Color of index 1*/",
                "#endif",
                "",
                format_bytes(payload),
                "};",
                "",
                f"const lv_img_dsc_t {name} = {{",
                "  .header.cf = LV_IMG_CF_INDEXED_1BIT,",
                "  .header.always_zero = 0,",
                "  .header.reserved = 0,",
                f"  .header.w = {WIDTH},",
                f"  .header.h = {HEIGHT},",
                f"  .data_size = {data_size},",
                f"  .data = {name}_map,",
                "};",
                "",
            ]
        )
    return "\n".join(parts)


def generate_h(frames: list[tuple[str, list[int]]]) -> str:
    names = [name for name, _ in frames]
    parts = [
        "/*",
        " * Generated by tools/convert_nice_view_art.py.",
        " * SPDX-License-Identifier: MIT",
        " */",
        "",
        "#pragma once",
        "",
        "#include <lvgl.h>",
        "",
    ]
    parts.extend(f"LV_IMG_DECLARE({name});" for name in names)
    parts.extend(
        [
            "",
            f"#define ATMOS_ART_FRAME_COUNT {len(names)}",
            "",
            "static const lv_img_dsc_t *atmos_anim_imgs[] = {",
        ]
    )
    parts.extend(f"    &{name}," for name in names)
    parts.extend(["};", ""])
    return "\n".join(parts)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    parser.add_argument("images", nargs="+", type=Path)
    parser.add_argument("--output-c", required=True, type=Path)
    parser.add_argument("--output-h", required=True, type=Path)
    parser.add_argument("--preview-dir", type=Path)
    parser.add_argument("--preview-inverted", action="store_true")
    parser.add_argument("--prefix", default="atmos")
    parser.add_argument("--rotate", choices=[0, 90, 180, 270], default=0, type=int)
    parser.add_argument("--safe-width", default=WIDTH, type=int)
    parser.add_argument("--margin", default=0, type=int)
    parser.add_argument("--threshold", default=220, type=int)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    frames: list[tuple[str, list[int]]] = []

    if args.preview_dir:
        args.preview_dir.mkdir(parents=True, exist_ok=True)

    seen: set[str] = set()
    for image_path in args.images:
        name = c_ident(image_path, args.prefix)
        base = name
        counter = 2
        while name in seen:
            name = f"{base}_{counter}"
            counter += 1
        seen.add(name)

        mono = fit_to_canvas(image_path, args.threshold, args.rotate)
        mono = constrain_to_safe_area(mono, args.safe_width, args.margin)
        frames.append((name, pack_indexed_1bit(mono)))
        if args.preview_dir:
            preview = mono.convert("L")
            if args.preview_inverted:
                preview = ImageOps.invert(preview)
            preview.save(args.preview_dir / f"{name}.png")

    args.output_c.parent.mkdir(parents=True, exist_ok=True)
    args.output_h.parent.mkdir(parents=True, exist_ok=True)
    args.output_c.write_text(generate_c(frames), encoding="utf-8")
    args.output_h.write_text(generate_h(frames), encoding="utf-8")


if __name__ == "__main__":
    main()
